version: '3'

services:
  mysql:
    container_name: mysql_server
    image: mysql:8.2.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=imserso_database
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - ./tablas.sql:/docker-entrypoint-initdb.d/tablas.sql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql

volumes:
  mysql_data:
